/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.dbConnection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Yasiru
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Admin_logIn_page
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_DisplayLogin = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        btn_Submit = new javax.swing.JButton();
        lbl_accountStatus = new javax.swing.JLabel();
        lbl_signin = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblwallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_DisplayLogin.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lbl_DisplayLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DisplayLogin.setText("SIGN UP");
        getContentPane().add(lbl_DisplayLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 260, 70));

        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 280, 50));

        pf_password.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 280, 50));

        btn_Submit.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btn_Submit.setText("SUBMIT");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 280, 60));

        lbl_accountStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_accountStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_accountStatus.setText("Do You Have An Account ?");
        getContentPane().add(lbl_accountStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        lbl_signin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_signin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_signin.setText("SIGN IN");
        lbl_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_signinMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 150, -1));

        lblpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(255, 255, 255));
        lblpassword.setText("PASSWORD");
        getContentPane().add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 50));

        lblusername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setText("USERNAME");
        getContentPane().add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 150, 110, 60));

        lblwallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SignUp.jpg"))); // NOI18N
        getContentPane().add(lblwallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed

        String username,Password;
        username=txt_username.getText();
        Password=pf_password.getText();
        try
        {
        Statement st=dbConnection.createDbConnection().createStatement();
        int row_count=st.executeUpdate("insert into user values('"+username+"','"+Password+"')");
        if(row_count>0)
         {
           JOptionPane.showMessageDialog(null, "Succesfully Completed.");
           Login_Page login_Page=new Login_Page();
           login_Page.setVisible(true);
           this.setVisible(false);
         }
        else
         {
           JOptionPane.showMessageDialog(null, "Please Try Again later...");
           Login_Page login_Page=new Login_Page();
           login_Page.setVisible(true);
           this.setVisible(false);
         }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
          
        
        
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void lbl_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseClicked
        // TODO add your handling code here:
      Login_Page l1=new Login_Page();
      l1.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_lbl_signinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Submit;
    private javax.swing.JLabel lbl_DisplayLogin;
    private javax.swing.JLabel lbl_accountStatus;
    private javax.swing.JLabel lbl_signin;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JLabel lblwallpaper;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
